import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,ArrowUpRight,Bell,ChevronDown,CircleHelp,Clock3,Home,KeyRound,MapPin,Menu,MoreHorizontal,Search,Settings2,ShieldCheck,Sparkles,UserRound,WalletCards,Wrench,X,Building2,Users,BriefcaseBusiness,CheckCircle2,AlertCircle,Layers3,Plus}from"lucide-react";
import"./styles.css";

type Section="Home"|"Places"|"Services"|"Activity"|"Workspaces"|"Identity";
const nav:[Section,React.ElementType][]= [["Home",Home],["Places",MapPin],["Services",Layers3],["Activity",Activity],["Workspaces",BriefcaseBusiness]];
const services=[["BeatAccess","Access and entry",ShieldCheck],["BeatHome","Home operations",Home],["BeatMaintenance","Maintenance",Wrench],["BeatVisitor","Visitor access",Users],["BeatFacility","Facilities",Building2],["BeatPay","Payments",WalletCards]];

function Logo(){return <div className="brand"><span className="brand-mark"><span/></span><b>LegaKeys</b></div>}
function Status({children,green=false}:{children:React.ReactNode;green?:boolean}){return <span className={"status "+(green?"green":"")}><i/>{children}</span>}
function SectionPage({children}:{children:React.ReactNode}){return <section className="page-section">{children}</section>}

function App(){
 const[section,setSection]=useState<Section>("Home"),[menu,setMenu]=useState(false),[more,setMore]=useState(false),[search,setSearch]=useState(false),[assistant,setAssistant]=useState(false),[identity,setIdentity]=useState(false),[context,setContext]=useState(false);
 const[liveServices,setLiveServices]=useState<any[]>([]),[dbState,setDbState]=useState("UNKNOWN");
 useEffect(()=>{fetch("/api/health",{credentials:"include"}).then(r=>r.json()).then(x=>setDbState(x.state??"UNKNOWN")).catch(()=>setDbState("UNAVAILABLE")); fetch("/api/services",{credentials:"include"}).then(r=>r.ok?r.json():null).then(x=>setLiveServices(x?.data??[])).catch(()=>setLiveServices([]));},[]);
 const subtitle:Record<Section,string>={Home:"Your identity, places, services and decisions — in one governed ecosystem.",Places:"Understand where you belong and what is connected.",Services:"Declared capabilities, available through governed access.",Activity:"A traceable record of what happened.",Workspaces:"Operate in the context you are authorized to use.",Identity:"Your identity, participation and trust state."};
 const go=(s:Section)=>{setSection(s);setMenu(false)};
 return <div className="app">
  <header className="topbar">
   <button className="mobile-menu icon" onClick={()=>setMenu(!menu)} aria-label="Open navigation"><Menu size={20}/></button><Logo/>
   <div className="context-wrap"><button className="context" onClick={()=>setContext(!context)}><span className="context-icon"><MapPin size={15}/></span><span><b>Current context</b><small>Choose a context</small></span><ChevronDown size={15}/></button>{context&&<div className="popover context-pop"><b>Context</b><p>Context changes what LegaKeys can show. It never grants authority.</p><button><UserRound size={15}/>Personal <small>Declared</small></button><button><Building2 size={15}/>Community <small>Not connected</small></button></div>}</div>
   <div className="top-actions"><button className="search" onClick={()=>setSearch(true)}><Search size={17}/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon" onClick={()=>setAssistant(true)} aria-label="Constantyna"><Sparkles size={18}/></button><button className="icon notification" aria-label="Notifications"><Bell size={18}/><i/></button><button className="identity-chip" onClick={()=>setIdentity(true)}><span className="avatar">K</span><ChevronDown size={13}/></button><button className="icon" onClick={()=>setMore(!more)} aria-label="More"><MoreHorizontal size={19}/></button></div>
   {more&&<div className="popover more-pop"><button><Settings2 size={16}/>Settings</button><button><CircleHelp size={16}/>Help & guidance</button><button><ShieldCheck size={16}/>Security & sessions</button></div>}
  </header>
  <aside className={"sidebar "+(menu?"open":"")}><div className="sidebar-scroll"><div className="nav-section"><label>Navigate</label>{nav.map(([name,Icon])=><button key={name} className={"nav-item "+(section===name?"active":"")} onClick={()=>go(name)}><Icon size={18}/><span>{name}</span></button>)}</div><div className="nav-section"><label>Your space</label><button className={"nav-item "+(section==="Identity"?"active":"")} onClick={()=>go("Identity")}><KeyRound size={18}/>Identity</button><button className="nav-item" onClick={()=>setAssistant(true)}><Sparkles size={18}/>Constantyna <em>AI</em></button></div><div className="trust-card"><ShieldCheck size={17}/><div><b>Governed by design</b><small>Authorization remains the execution boundary.</small></div></div></div></aside>
  <main className="main"><div className="content"><section className="hero"><div><label className="eyebrow">LEGAKEYS · {section.toUpperCase()}</label><h1>{section==="Home"?"Good to see you":section}</h1><p>{subtitle[section]}</p></div><div className="hero-actions"><Status green={dbState==="CONNECTED"}>{dbState==="CONNECTED"?"Neon connected":dbState==="NOT_CONFIGURED"?"Neon not configured":dbState==="UNAVAILABLE"?"Neon unavailable":"Checking Neon"}</Status><button className="primary" onClick={()=>setAssistant(true)}><Sparkles size={16}/>Ask Constantyna</button></div></section>
   {section==="Home"&&<><section className="feature-grid"><article className="feature dark"><div className="kicker"><Sparkles size={14}/>Intelligence</div><h2>What matters now?</h2><p>Nothing is presented as live or verified until LegaKeys has a source and provenance for it.</p><button className="text" onClick={()=>setAssistant(true)}>Ask Constantyna <ArrowUpRight size={15}/></button></article><article className="feature light"><div className="kicker"><ShieldCheck size={14}/>Trust boundary</div><h2>Every important decision is explicit.</h2><p className="trust"><CheckCircle2 size={16}/>Identity ≠ authorization</p><p className="trust"><CheckCircle2 size={16}/>Capability ≠ authority</p><p className="trust"><CheckCircle2 size={16}/>Interface ≠ execution</p></article></section>
   <Block title="Start here" desc="Move through LegaKeys without learning the architecture underneath it."><div className="action-grid">{[["Places","See your connected places",MapPin],["Services","Explore declared capabilities",Layers3],["Activity","Review verified history",Activity],["Workspaces","Operate in your scopes",BriefcaseBusiness]].map(([n,d,I])=><button className="action-card" key={n as string} onClick={()=>go(n as Section)}><I size={18}/><span><b>{n as string}</b><small>{d as string}</small></span><ArrowUpRight size={15}/></button>)}</div></Block>
   <Block title="Services" desc="LegaKeys-owned services. Providers are fulfillment connections, never the service owner." action={<button className="ghost" onClick={()=>go("Services")}>View all <ArrowUpRight size={14}/></button>}><div className="service-grid">{(liveServices.length?liveServices:[]).slice(0,4).map((s)=><button className="service-card" key={s.service_id} onClick={()=>go("Services")}><span className="service-icon"><Layers3 size={18}/></span><span><b>{s.canonical_name}</b><small>{s.description||s.beat_code}</small></span><ArrowUpRight size={14}/></button>)}</div></Block></>}
   {section==="Services"&&<SectionPage><Notice title="Truthful service state">These are product capabilities, not invented provider availability. Live fulfillment appears only when a declared connection is verified.</Notice><div className="service-grid wide">{liveServices.length?liveServices.map((s)=><button className="service-card" key={s.service_id}><span className="service-icon"><Layers3 size={18}/></span><span><b>{s.canonical_name}</b><small>{s.description||s.beat_code}</small><em>{s.truth_state||"UNKNOWN"} · {s.lifecycle_state||"UNKNOWN"}</em></span><ArrowUpRight size={14}/></button>):<Notice title="No production services loaded">Neon is not connected or the production services table is empty. Nothing is invented in its place.</Notice>}</div></SectionPage>}
   {section==="Places"&&<SectionPage><Empty icon={<MapPin size={23}/>} title="No connected places yet" body="When a place is connected to your participation, LegaKeys will show its structure, relationships, access points, services and verified state." action="Connect a place"/></SectionPage>}
   {section==="Activity"&&<SectionPage><div className="activity-list">{[["Authorization required","A consequential action will always show its scope before execution.","Policy",ShieldCheck],["No live events connected","Activity becomes populated when verified event sources are connected.","Unknown",Activity],["Context is explicit","Current place, time and relationship context are never silently assumed.","Declared",MapPin]].map(([t,b,s,I])=><article className="activity-row" key={t as string}><span className="activity-icon"><I size={16}/></span><div><b>{t as string}</b><p>{b as string}</p></div><Status green={s==="Declared"}>{s as string}</Status><Clock3 size={14}/></article>)}</div></SectionPage>}
   {section==="Workspaces"&&<SectionPage><div className="workspace-grid"><Workspace title="LegaKeys Operating" desc="Internal operating environment for authorized LegaKeys work." available/><Workspace title="Community Operating" desc="Appears only when an authorized community context exists."/></div><Notice title="Workspace visibility is not authority">Membership, roles and capabilities are scoped. Consequential actions still pass through authorization and the Action Runtime.</Notice></SectionPage>}
   {section==="Identity"&&<SectionPage><div className="identity-panel"><div className="identity-main"><span className="avatar large">K</span><div><label className="eyebrow">PARTICIPANT</label><h2>Identity & participation</h2><p>Your identity is separate from your account, participation, roles and authority.</p></div></div><div className="identity-rows">{[["BeatIdentity","Protected"],["Account","Session-bound"],["Participation","Contextual"],["Authorization","Evaluated per action"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div></div></SectionPage>}
  </div></main>
  <nav className="bottom-nav">{nav.map(([n,I])=><button className={section===n?"active":""} onClick={()=>go(n)} key={n}><I size={18}/><span>{n}</span></button>)}</nav>
  {search&&<div className="overlay" onMouseDown={()=>setSearch(false)}><div className="command" onMouseDown={e=>e.stopPropagation()}><div className="command-search"><Search size={18}/><input autoFocus placeholder="Search people, places, services, activity..."/><kbd>ESC</kbd></div><div className="command-list"><label>Suggested</label><button onClick={()=>{setSearch(false);setAssistant(true)}}><Sparkles size={16}/>Ask Constantyna<small>Understand something</small></button><button onClick={()=>{setSearch(false);go("Services")}}><Layers3 size={16}/>Services<small>Declared capabilities</small></button><button onClick={()=>{setSearch(false);go("Activity")}}><Activity size={16}/>Activity<small>Events and evidence</small></button></div></div></div>}
  {assistant&&<div className="drawer-backdrop" onMouseDown={()=>setAssistant(false)}><aside className="assistant" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="assistant-mark"><Sparkles size={17}/></span><div><b>Constantyna</b><small>Human intelligence</small></div></div><button className="icon dark-icon" onClick={()=>setAssistant(false)}><X size={18}/></button></div><div className="assistant-body"><div className="assistant-intro"><span className="assistant-avatar"><Sparkles size={20}/></span><h2>How can I help you understand LegaKeys?</h2><p>I can explain, clarify, guide and prepare proposals. I cannot grant authority or execute consequential actions by myself.</p></div><div className="prompt-list"><button>What can I do here?</button><button>Show me my available services</button><button>Explain authorization</button></div></div><div className="assistant-input"><input placeholder="Ask Constantyna..."/><button className="primary" aria-label="Send"><ArrowUpRight size={15}/></button></div></aside></div>}
  {identity&&<div className="overlay" onMouseDown={()=>setIdentity(false)}><div className="identity-pop" onMouseDown={e=>e.stopPropagation()}><div className="identity-head"><span className="avatar large">K</span><div><b>Your identity</b><small>Protected participant context</small></div><button className="icon dark-icon" onClick={()=>setIdentity(false)}><X size={18}/></button></div><div className="identity-status"><ShieldCheck size={18}/><div><b>Trust boundary active</b><p>Authentication and authorization are separate. Every consequential action is evaluated in context.</p></div></div><button className="secondary full" onClick={()=>{setIdentity(false);go("Identity")}}>Open identity <ArrowUpRight size={15}/></button></div></div>}
 </div>
}
function Block({title,desc,action,children}:{title:string;desc:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="block"><div className="section-head"><div><h2>{title}</h2><p>{desc}</p></div>{action}</div>{children}</section>}
function Notice({title,children}:{title:string;children:React.ReactNode}){return <div className="notice"><AlertCircle size={18}/><div><b>{title}</b><p>{children}</p></div></div>}
function Empty({icon,title,body,action}:{icon:React.ReactNode;title:string;body:string;action:string}){return <div className="empty"><span>{icon}</span><h2>{title}</h2><p>{body}</p><button className="secondary"><Plus size={15}/>{action}</button></div>}
function Workspace({title,desc,available=false}:{title:string;desc:string;available?:boolean}){return <article className="workspace-card"><span className="workspace-icon"><BriefcaseBusiness size={18}/></span><div><Status green={available}>{available?"Available":"Not connected"}</Status><h2>{title}</h2><p>{desc}</p>{available&&<button className="text">Open workspace <ArrowUpRight size={14}/></button>}</div></article>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);