import React,{useEffect,useState}from"react";
import heroAsset from "../IMG_1575.jpeg";

import{createRoot}from"react-dom/client";
import{Activity,ArrowUpRight,Bell,ChevronDown,CircleHelp,Clock3,Home,KeyRound,Layers3,MapPin,Menu,MoreHorizontal,Search,Settings2,ShieldCheck,Sparkles,UserRound,WalletCards,Wrench,X,Building2,Users,BriefcaseBusiness,CheckCircle2,AlertCircle,Plus,Globe2,Brain,GitBranch,Zap,LockKeyhole,Compass,LogIn,UserPlus,Handshake,Moon,Sun,Palette}from"lucide-react";
import"./styles.css";

type Section="Home"|"Places"|"Services"|"Access"|"Payments"|"Activity"|"Workspaces"|"Identity"|"Intelligence"|"World"|"Execution";
const nav:[Section,React.ElementType][]= [["Home",Home],["Places",MapPin],["Services",Layers3],["Access",KeyRound],["Payments",WalletCards],["Activity",Activity]];
const services=[["BeatAccess","Access and entry",ShieldCheck],["BeatHome","Home operations",Home],["BeatMaintenance","Maintenance",Wrench],["BeatVisitor","Visitor access",Users],["BeatFacility","Facilities",Building2],["BeatPay","Payments",WalletCards]];
const deep=[["Workspaces","Operate in authorized scopes",BriefcaseBusiness],["Identity","Identity & participation",KeyRound],["Intelligence","GENESIS + Constantyna",Brain],["World","World + digital twin",Globe2],["Execution","Action → Event → Evidence",Zap]];

function Logo({light=false}:{light?:boolean}){return <div className={"brand "+(light?"brand-light":"")}><span className="brand-image brand-logo"><img src="/legakeys-logo-transparent.svg" alt="LegaKeys"/></span></div>}
function Status({children,green=false}:{children:React.ReactNode;green?:boolean}){return <span className={"status "+(green?"green":"")}><i/>{children}</span>}
function SectionPage({children}:{children:React.ReactNode}){return <section className="page-section">{children}</section>}

function Landing({onEnter}:{onEnter:()=>void}){
 const[auth,setAuth]=useState<"create"|"signin"|null>(null);
 const[join,setJoin]=useState(false);
 return <div className="landing">
  <header className="landing-bar"><Logo light/><div className="landing-actions"><button className="landing-link" onClick={()=>setAuth("signin")}>Sign in</button><button className="landing-primary" onClick={()=>setAuth("create")}><UserPlus size={15}/>Create account</button></div></header>
  <main className="landing-main">
   <section className="landing-hero"><div className="landing-copy"><div className="eyebrow light">YOUR IDENTITY. YOUR WORLD. ONE ECOSYSTEM.</div><h1>One place for the life you’re authorized to live.</h1><p>LegaKeys connects identity, places, access, services, payments, communities and intelligence in one governed ecosystem.</p><div className="landing-cta"><button className="landing-primary large" onClick={()=>setAuth("create")}><UserPlus size={17}/>Create your account</button><button className="landing-secondary large" onClick={()=>setJoin(true)}><Handshake size={17}/>Join a community</button></div><div className="landing-note"><ShieldCheck size={15}/>Authentication is not authorization. Consequential actions remain governed.</div></div><div className="hero-orbit"><img src={heroAsset} alt="LegaKeys visual emblem"/></div></section>
   <section className="landing-rail"><div><span><KeyRound size={16}/>Identity</span><b>One participant context</b></div><div><span><MapPin size={16}/>Places</span><b>Buildings, units & spaces</b></div><div><span><Layers3 size={16}/>Services</span><b>Declared LegaKeys capabilities</b></div><div><span><Brain size={16}/>Intelligence</span><b>Human + machine guidance</b></div></section>
   <section className="landing-section"><div className="section-intro"><div><div className="eyebrow">BUILT INTO THE PLATFORM</div><h2>Deep capability without the complexity.</h2></div><p>Discover the product surface first. The architecture stays underneath it.</p></div><div className="landing-cards">{[["Access","Controlled entry, visitors and governed permissions",KeyRound],["Services","Beat services across living, mobility, payments and commerce",Layers3],["Community","Join contexts without turning membership into authority",Users],["Intelligence","GENESIS observes and proposes; Constantyna explains and guides",Brain]].map(([t,d,I])=><article key={t as string} className="landing-card"><I size={19}/><h3>{t as string}</h3><p>{d as string}</p><ArrowUpRight size={15}/></article>)}</div></section>
   <section className="landing-bottom"><div><div className="eyebrow">EXPLORE THE PRODUCT</div><h2>See the full LegaKeys operating surface.</h2><p>You can enter the product preview without inventing data or claiming unavailable providers.</p></div><button className="landing-primary" onClick={onEnter}>Explore LegaKeys <ArrowUpRight size={15}/></button></section>
  </main>
  {auth&&<div className="overlay" onMouseDown={()=>setAuth(null)}><div className="auth-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAuth(null)}><X size={18}/></button><Logo/><div className="auth-icon">{auth==="create"?<UserPlus size={21}/>:<LogIn size={21}/>}</div><h2>{auth==="create"?"Create your LegaKeys account":"Welcome back"}</h2><p>{auth==="create"?"Start with your identity. Participation, context and authority are established separately.":"Sign in to continue to your governed LegaKeys space."}</p><label>Email or phone<input placeholder="Enter your email or phone"/></label>{auth==="create"&&<label>Full legal name<input placeholder="Your legal name"/></label>}<button className="primary full" onClick={()=>{setAuth(null);onEnter()}}>{auth==="create"?"Continue":"Continue"} <ArrowUpRight size={15}/></button><small className="auth-foot">Secure authentication/session wiring remains a separate production integration gate. No account is fabricated by this preview.</small></div></div>}
  {join&&<div className="overlay" onMouseDown={()=>setJoin(false)}><div className="auth-modal join-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setJoin(false)}><X size={18}/></button><Logo/><div className="auth-icon"><Handshake size={21}/></div><h2>Join a community</h2><p>Enter a community invitation or approved joining code. Membership never silently grants authority.</p><label>Invitation or join code<input placeholder="e.g. TSAVO-..." /></label><button className="primary full" onClick={()=>{setJoin(false);onEnter()}}>Review invitation <ArrowUpRight size={15}/></button></div></div>}
 </div>
}

function App(){
 const[preview,setPreview]=useState(true);
 type Theme="dark"|"light"|"navy";
 const[theme,setTheme]=useState<Theme>(()=>{const saved=localStorage.getItem("legakeys-theme");return saved==="dark"||saved==="light"||saved==="navy"?saved:"navy"});
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme==="light"?"light":"dark";localStorage.setItem("legakeys-theme",theme)},[theme]);
 const[section,setSection]=useState<Section>("Home"),[menu,setMenu]=useState(false),[more,setMore]=useState(false),[search,setSearch]=useState(false),[assistant,setAssistant]=useState(false),[identity,setIdentity]=useState(false),[context,setContext]=useState(false);
 const[liveServices,setLiveServices]=useState<any[]>([]),[dbState,setDbState]=useState("UNKNOWN");
 useEffect(()=>{fetch("/api/health",{credentials:"include"}).then(r=>r.json()).then(x=>setDbState(x.state??"UNKNOWN")).catch(()=>setDbState("UNAVAILABLE"));fetch("/api/services",{credentials:"include"}).then(r=>r.ok?r.json():null).then(x=>setLiveServices(x?.data??[])).catch(()=>setLiveServices([]));},[]);
 if(preview)return <Landing onEnter={()=>setPreview(false)}/>;
 const subtitle:Record<Section,string>={Home:"Your identity, places, services and decisions — in one governed ecosystem.",Places:"Understand where you belong and what is connected.",Services:"Declared capabilities, available through governed access.",Access:"Entry, visitors and permissions are evaluated in context.",Payments:"Payment intent, authorization, execution and reconciliation.",Activity:"A traceable record of what happened.",Workspaces:"Operate in the context you are authorized to use.",Identity:"Your identity, participation and trust state.",Intelligence:"GENESIS + Constantyna: intelligence without self-granted authority.",World:"Places, physical entities, relationships and digital-twin state.",Execution:"Intent → Proposal → Authorization → Action → Event → Evidence."};
 const go=(s:Section)=>{setSection(s);setMenu(false)};
 return <div className="app">
  <header className="topbar"><button className="mobile-menu icon" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><Logo/><div className="context-wrap"><button className="context" onClick={()=>setContext(!context)}><span className="context-icon"><MapPin size={15}/></span><span><b>Current context</b><small>Choose a context</small></span><ChevronDown size={15}/></button>{context&&<div className="popover context-pop"><b>Context</b><p>Context changes what LegaKeys can show. It never grants authority.</p><button><UserRound size={15}/>Personal <small>Declared</small></button><button><Building2 size={15}/>Community <small>Not connected</small></button></div>}</div><div className="top-actions"><button className="search" onClick={()=>setSearch(true)}><Search size={17}/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon" onClick={()=>setAssistant(true)}><Sparkles size={18}/></button><button className="icon notification"><Bell size={18}/><i/></button><button className="identity-chip" onClick={()=>setIdentity(true)}><span className="avatar">K</span><ChevronDown size={13}/></button><button className="icon" onClick={()=>setMore(!more)}><MoreHorizontal size={19}/></button></div>{more&&<div className="popover more-pop"><div className="theme-menu"><b>Appearance</b><small>Choose how LegaKeys looks everywhere.</small><div className="theme-options"><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}><Moon size={15}/><span>Dark</span></button><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}><Sun size={15}/><span>White</span></button><button className={theme==="navy"?"selected":""} onClick={()=>setTheme("navy")}><Palette size={15}/><span>Navy</span></button></div></div><button><Settings2 size={16}/>Settings</button><button><CircleHelp size={16}/>Help & guidance</button><button><ShieldCheck size={16}/>Security & sessions</button></div>}</header>
  <aside className={"sidebar "+(menu?"open":"")}><div className="sidebar-scroll"><div className="nav-section"><label>Navigate</label>{nav.map(([name,Icon])=><button key={name} className={"nav-item "+(section===name?"active":"")} onClick={()=>go(name)}><Icon size={18}/><span>{name}</span></button>)}</div><div className="nav-section"><label>Deep LegaKeys</label>{deep.map(([name,desc,Icon])=><button key={name as string} className={"nav-item "+(section===name?"active":"")} onClick={()=>go(name as Section)}><Icon size={18}/><span>{name as string}</span></button>)}</div><div className="trust-card"><ShieldCheck size={17}/><div><b>Governed by design</b><small>Authorization remains the execution boundary.</small></div></div></div></aside>
  <main className="main"><div className="content"><section className="hero"><div><label className="eyebrow">LEGAKEYS · {section.toUpperCase()}</label><h1>{section==="Home"?"Good to see you":section}</h1><p>{subtitle[section]}</p></div><div className="hero-actions"><Status green={dbState==="CONNECTED"}>{dbState==="CONNECTED"?"Neon connected":dbState==="NOT_CONFIGURED"?"Neon not configured":dbState==="UNAVAILABLE"?"Neon unavailable":"Checking Neon"}</Status><button className="primary" onClick={()=>setAssistant(true)}><Sparkles size={16}/>Ask Constantyna</button></div></section>
   {section==="Home"&&<><section className="feature-grid"><article className="feature dark"><div className="kicker"><Sparkles size={14}/>Intelligence</div><h2>What matters now?</h2><p>Nothing is presented as live or verified until LegaKeys has a source and provenance for it.</p><button className="text" onClick={()=>setAssistant(true)}>Ask Constantyna <ArrowUpRight size={15}/></button></article><article className="feature light"><div className="kicker"><ShieldCheck size={14}/>Trust boundary</div><h2>Every important decision is explicit.</h2><p className="trust"><CheckCircle2 size={16}/>Identity ≠ authorization</p><p className="trust"><CheckCircle2 size={16}/>Capability ≠ authority</p><p className="trust"><CheckCircle2 size={16}/>Interface ≠ execution</p></article></section><Block title="Start here" desc="Move through LegaKeys without learning the architecture underneath it."><div className="action-grid">{[["Places","See connected places",MapPin],["Services","Explore declared capabilities",Layers3],["Access","Access and visitor controls",KeyRound],["Payments","Payment infrastructure",WalletCards]].map(([n,d,I])=><button className="action-card" key={n as string} onClick={()=>go(n as Section)}><I size={18}/><span><b>{n as string}</b><small>{d as string}</small></span><ArrowUpRight size={15}/></button>)}</div></Block><Block title="Services" desc="LegaKeys-owned services. Providers are fulfillment connections, never the service owner." action={<button className="ghost" onClick={()=>go("Services")}>View all <ArrowUpRight size={14}/></button>}><div className="service-grid">{(liveServices.length?liveServices:services).slice(0,6).map((s:any)=><button className="service-card" key={s.service_id||s[0]} onClick={()=>go("Services")}><span className="service-icon"><Layers3 size={18}/></span><span><b>{s.canonical_name||s[0]}</b><small>{s.description||s[1]}</small></span><ArrowUpRight size={14}/></button>)}</div></Block><Block title="Deep platform" desc="The architecture is not hidden; it is simply revealed when useful."><div className="action-grid deep-grid">{deep.map(([n,d,I])=><button className="action-card" key={n as string} onClick={()=>go(n as Section)}><I size={18}/><span><b>{n as string}</b><small>{d as string}</small></span><ArrowUpRight size={15}/></button>)}</div></Block></>}
   {section==="Services"&&<SectionPage><Notice title="Truthful service state">These are product capabilities, not invented provider availability. Live fulfillment appears only when a declared connection is verified.</Notice><div className="service-grid wide">{(liveServices.length?liveServices:services).map((s:any)=><button className="service-card" key={s.service_id||s[0]}><span className="service-icon"><Layers3 size={18}/></span><span><b>{s.canonical_name||s[0]}</b><small>{s.description||s[1]}</small><em>{s.truth_state||"DECLARED"} · {s.lifecycle_state||"ACTIVE"}</em></span><ArrowUpRight size={14}/></button>)}</div></SectionPage>}
   {section==="Places"&&<SectionPage><DataSurface icon={<MapPin size={23}/>} title="Places & living infrastructure" body="World → Country → City → Community → Phase → Building → Floor → Unit → Common Area → Facility → Workspace → Access Point." items={["Connected places","Relationships","Buildings & units","Facilities","Access points"]}/></SectionPage>}
   {section==="Access"&&<SectionPage><DataSurface icon={<LockKeyhole size={23}/>} title="BeatAccess" body="Access is a governed capability. Authentication proves a credential; authorization decides whether an action is permitted in context." items={["Access points","Visitor invitations","Credentials","Authorization decisions","Access events"]}/></SectionPage>}
   {section==="Payments"&&<SectionPage><DataSurface icon={<WalletCards size={23}/>} title="BeatPay" body="Payment intent, authorization, execution and reconciliation are separated. Provider connections are adapters, not the platform's source of truth." items={["Payment intents","Authorization","Execution","Provider adapters","Reconciliation"]}/></SectionPage>}
   {section==="Activity"&&<SectionPage><div className="activity-list">{[["Authorization required","A consequential action always exposes its scope before execution.","Policy",ShieldCheck],["Event / evidence trail","Events record what happened; evidence supports historical truth.","Verified",Activity],["Context is explicit","Place, time and relationship context are never silently assumed.","Declared",MapPin]].map(([t,b,s,I])=><article className="activity-row" key={t as string}><span className="activity-icon"><I size={16}/></span><div><b>{t as string}</b><p>{b as string}</p></div><Status green={s==="Verified"}>{s as string}</Status><Clock3 size={14}/></article>)}</div></SectionPage>}
   {(section==="Workspaces"||section==="Identity"||section==="Intelligence"||section==="World"||section==="Execution")&&<SectionPage><DataSurface icon={section==="Intelligence"?<Brain size={23}/>:section==="World"?<Globe2 size={23}/>:section==="Execution"?<GitBranch size={23}/>:section==="Identity"?<KeyRound size={23}/>:<BriefcaseBusiness size={23}/>} title={section==="Workspaces"?"Operating workspaces":section} body={subtitle[section]} items={section==="Execution"?["Intent","Proposal","Authorization","Action","Event","Evidence","Outcome"]:section==="Intelligence"?["GENESIS runs","Findings","Proposals","Constantyna sessions","Human understanding"]:section==="World"?["World entities","Places","Relationships","Observations","Digital twins"]:section==="Identity"?["BeatIdentity","Account","Session","Participant","Participation"]:["LegaKeys operating","Community operating","Workspace memberships","Scoped capabilities"]}/><Notice title="Visibility is not authority">This surface exposes the platform model without implying permission to execute consequential actions.</Notice></SectionPage>}
  </div></main><nav className="bottom-nav">{nav.slice(0,5).map(([n,I])=><button className={section===n?"active":""} onClick={()=>go(n)} key={n}><I size={18}/><span>{n}</span></button>)}</nav>
  {search&&<div className="overlay" onMouseDown={()=>setSearch(false)}><div className="command" onMouseDown={e=>e.stopPropagation()}><div className="command-search"><Search size={18}/><input autoFocus placeholder="Search people, places, services, activity..."/><kbd>ESC</kbd></div><div className="command-list"><label>Suggested</label>{[["Services",Layers3],["Access",KeyRound],["Intelligence",Brain],["Execution",Zap]].map(([n,I])=><button key={n as string} onClick={()=>{setSearch(false);go(n as Section)}}><I size={16}/>{n as string}<small>Explore</small></button>)}</div></div></div>}
  {assistant&&<div className="drawer-backdrop" onMouseDown={()=>setAssistant(false)}><aside className="assistant" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="assistant-mark"><Sparkles size={17}/></span><div><b>Constantyna</b><small>Human intelligence</small></div></div><button className="icon dark-icon" onClick={()=>setAssistant(false)}><X size={18}/></button></div><div className="assistant-body"><div className="assistant-intro"><span className="assistant-avatar"><Sparkles size={20}/></span><h2>Understand LegaKeys with me.</h2><p>I can explain, clarify, guide and prepare proposals. I cannot grant authority or execute consequential actions by myself.</p></div><div className="prompt-list"><button onClick={()=>{setAssistant(false);go("Services")}}>Show me available services</button><button onClick={()=>{setAssistant(false);go("Execution")}}>Explain authorization and execution</button><button onClick={()=>{setAssistant(false);go("World")}}>Show the world model</button></div></div><div className="assistant-input"><input placeholder="Ask Constantyna..."/><button className="primary"><ArrowUpRight size={15}/></button></div></aside></div>}
  {identity&&<div className="overlay" onMouseDown={()=>setIdentity(false)}><div className="identity-pop" onMouseDown={e=>e.stopPropagation()}><div className="identity-head"><span className="avatar large">K</span><div><b>Your identity</b><small>Protected participant context</small></div><button className="icon dark-icon" onClick={()=>setIdentity(false)}><X size={18}/></button></div><div className="identity-status"><ShieldCheck size={18}/><div><b>Trust boundary active</b><p>Authentication and authorization are separate. Every consequential action is evaluated in context.</p></div></div><button className="secondary full" onClick={()=>{setIdentity(false);go("Identity")}}>Open identity <ArrowUpRight size={15}/></button></div></div>}
 </div>
}
function Block({title,desc,action,children}:{title:string;desc:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="block"><div className="section-head"><div><h2>{title}</h2><p>{desc}</p></div>{action}</div>{children}</section>}
function Notice({title,children}:{title:string;children:React.ReactNode}){return <div className="notice"><AlertCircle size={18}/><div><b>{title}</b><p>{children}</p></div></div>}
function DataSurface({icon,title,body,items}:{icon:React.ReactNode;title:string;body:string;items:string[]}){return <div className="data-surface"><div className="data-head"><span>{icon}</span><div><h2>{title}</h2><p>{body}</p></div></div><div className="data-items">{items.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><ArrowUpRight size={14}/></div>)}</div></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
